package ui

import "fmt"

// HelpText is `setfree help`'s entire output. It's curated by hand — no
// autogenerated flag wall — because the command surface is small enough
// that a real person reading it top to bottom is a better experience than
// an exhaustive reference.
const HelpText = `SetFree — Any coding CLI. Any gateway. Any model.

Usage:
  setfree <cli> [args...]
  setfree config [show|set|reset]
  setfree version

Examples:
  setfree claude
  setfree claude .
  setfree codex .

Supported CLIs:
  claude   Claude Code
  codex    Codex

Environment variables (override saved config for one run):
  SETFREE_BASE_URL   gateway base URL
  SETFREE_API_KEY    gateway API key
  SETFREE_MODEL      model override

Run 'setfree' with no arguments for status and detected CLIs.
`

// NotInstalledError formats the message shown when a supported CLI isn't
// on PATH — actionable, not a raw exec error.
func NotInstalledError(displayName, key string) error {
	return fmt.Errorf("%s wasn't found.\n\nInstall %s first, then run:\n\n  setfree %s", displayName, displayName, key)
}

// UnsupportedError formats the message for a recognized-but-unimplemented
// CLI (e.g. gemini, aider).
func UnsupportedError(displayName, key string) error {
	return fmt.Errorf("%s isn't supported by SetFree yet.\n\nIt's on the roadmap — see https://github.com/mindsdb/setfree for status.", displayName)
}

// UnknownCLIError formats the message for a name SetFree doesn't recognize
// at all.
func UnknownCLIError(name string) error {
	return fmt.Errorf("%q isn't a coding CLI SetFree knows about.\n\nRun 'setfree help' to see what's supported.", name)
}

// NoGatewayError formats the message shown when configuration is required
// but SetFree is running non-interactively (so it can't prompt).
func NoGatewayError() error {
	return fmt.Errorf("No gateway is configured, and input isn't a terminal so SetFree can't ask.\n\nRun:\n  setfree config\n\nor set:\n  SETFREE_BASE_URL and SETFREE_API_KEY")
}
